language: ruby

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq bats; fi

jobs:
  include:
    - rbenv: ruby-2.1.0
      script: RUBY_VERSION="2.1.0" bats tests-1.sh
    - rbenv: ruby-2.7.0
      script: RUBY_VERSION="2.7.0" bats tests-2.sh
      