language: ruby

os:
  - linux

rvm:
  - 2.0
  - 2.7.0

rbenv:
  - ruby-2.1.0
  - ruby-2.7.0

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq bats; fi

script:
  - bats tests.sh
  - ruby -v
  - RBENV_VERSION=2.1.0 ruby -v
  - RBENV_VERSION=2.7.0 ruby -v